/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projectdb;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MICHAL
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    String connector = "org.postgresql.Driver";
    String url = "jdbc:postgresql://localhost:5432/zoo";
    String user = "testuser";
    String password = "password";

    public Home() {
        initComponents();
        centerFrame();
        jPanel_edit.setVisible(false);
        lbl_find.setVisible(false);
        txt_find.setVisible(false);
        btn_hide.setVisible(false);
        btn_looking.setVisible(false);
        jPanel3.setVisible(false);
        jButton1.setVisible(false);
        btn_rst2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_edit = new javax.swing.JPanel();
        lbl_1 = new javax.swing.JLabel();
        txt_1 = new javax.swing.JTextField();
        lbl_2 = new javax.swing.JLabel();
        txt_2 = new javax.swing.JTextField();
        lbll_3 = new javax.swing.JLabel();
        txt_3 = new javax.swing.JTextField();
        lbl_4 = new javax.swing.JLabel();
        txt_4 = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_rmv = new javax.swing.JButton();
        btn_rst = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_list = new javax.swing.JPanel();
        lbl_list = new javax.swing.JLabel();
        btn_discover = new javax.swing.JPanel();
        lbl_discover = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();
        lbl_find = new javax.swing.JLabel();
        txt_find = new javax.swing.JTextField();
        btn_looking = new javax.swing.JButton();
        btn_hide = new javax.swing.JButton();
        btn_rst2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(76, 41, 211));
        jPanel2.setPreferredSize(new java.awt.Dimension(286, 525));

        jPanel_edit.setBackground(new java.awt.Color(76, 41, 211));

        lbl_1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_1.setForeground(new java.awt.Color(204, 204, 204));
        lbl_1.setText("Name");

        txt_1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_1.setPreferredSize(new java.awt.Dimension(4, 20));

        lbl_2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_2.setForeground(new java.awt.Color(204, 204, 204));
        lbl_2.setText("Age");

        txt_2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_2.setPreferredSize(new java.awt.Dimension(4, 20));

        lbll_3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbll_3.setForeground(new java.awt.Color(204, 204, 204));
        lbll_3.setText("Cage number");

        txt_3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_3.setPreferredSize(new java.awt.Dimension(4, 20));

        lbl_4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_4.setForeground(new java.awt.Color(204, 204, 204));
        lbl_4.setText("Required cage size");

        txt_4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_4.setPreferredSize(new java.awt.Dimension(4, 20));

        btn_add.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_add.setText("Add");
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addMousePressed(evt);
            }
        });
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_rmv.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_rmv.setText("Kill");
        btn_rmv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_rmvMousePressed(evt);
            }
        });
        btn_rmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rmvActionPerformed(evt);
            }
        });

        btn_rst.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_rst.setText("Clear");
        btn_rst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_rstMousePressed(evt);
            }
        });
        btn_rst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rstActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_update.setText("Update");
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_updateMousePressed(evt);
            }
        });

        jButton1.setText("^");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_editLayout = new javax.swing.GroupLayout(jPanel_edit);
        jPanel_edit.setLayout(jPanel_editLayout);
        jPanel_editLayout.setHorizontalGroup(
            jPanel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_editLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_editLayout.createSequentialGroup()
                            .addComponent(lbl_4)
                            .addGap(86, 86, 86))
                        .addGroup(jPanel_editLayout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(lbl_1)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_editLayout.createSequentialGroup()
                            .addGroup(jPanel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_rmv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_rst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_update, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(110, 110, 110)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_editLayout.createSequentialGroup()
                        .addComponent(lbl_2)
                        .addGap(129, 129, 129))))
            .addGroup(jPanel_editLayout.createSequentialGroup()
                .addGroup(jPanel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_editLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_editLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lbll_3))
                    .addGroup(jPanel_editLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_editLayout.setVerticalGroup(
            jPanel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_editLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbll_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_rst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_rmv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update)
                    .addComponent(jButton1)))
        );

        btn_list.setBackground(new java.awt.Color(76, 41, 211));
        btn_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_listMousePressed(evt);
            }
        });
        btn_list.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_list.setBackground(new java.awt.Color(222, 222, 222));
        lbl_list.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_list.setForeground(new java.awt.Color(204, 204, 204));
        lbl_list.setText("Show the list of animals");
        btn_list.add(lbl_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btn_discover.setBackground(new java.awt.Color(76, 41, 211));
        btn_discover.setPreferredSize(new java.awt.Dimension(0, 75));
        btn_discover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_discoverMousePressed(evt);
            }
        });
        btn_discover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_discover.setBackground(new java.awt.Color(222, 222, 222));
        lbl_discover.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_discover.setForeground(new java.awt.Color(204, 204, 204));
        lbl_discover.setText("Edit an animal");
        btn_discover.add(lbl_discover, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 161, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_discover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_list, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_discover, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "species_name", "age", "cage_number", "cage_size"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(10, 10));
        jTable1.setRowHeight(30);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblStatus.setBackground(new java.awt.Color(204, 204, 204));
        lblStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(204, 204, 204));
        lblStatus.setText("Status:");

        lbl_find.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_find.setForeground(new java.awt.Color(0, 0, 0));
        lbl_find.setText("Find an animal by its species:");

        txt_find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_findKeyReleased(evt);
            }
        });

        btn_looking.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_looking.setText("Looking for some animal?");
        btn_looking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_lookingMousePressed(evt);
            }
        });
        btn_looking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lookingActionPerformed(evt);
            }
        });

        btn_hide.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_hide.setText("Hide");
        btn_hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_hideMousePressed(evt);
            }
        });

        btn_rst2.setText("Clear");
        btn_rst2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_rst2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_find)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_find, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_rst2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_hide)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_looking))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_find)
                    .addComponent(txt_find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_looking)
                    .addComponent(btn_hide)
                    .addComponent(btn_rst2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMousePressed
        // TODO add your handling code here:
        if (txt_1.getText().isEmpty() || txt_2.getText().isEmpty() || txt_3.getText().isEmpty() || txt_4.getText().isEmpty()) {
            lblStatus.setForeground(Color.red);
            lblStatus.setText("Enter all details!");
        } else {
            saveData();
        }
    }//GEN-LAST:event_btn_addMousePressed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_rmvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rmvMousePressed
        // TODO add your handling code here:
        remove();
    }//GEN-LAST:event_btn_rmvMousePressed

    private void btn_rmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rmvActionPerformed

    }//GEN-LAST:event_btn_rmvActionPerformed

    private void btn_rstMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rstMousePressed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btn_rstMousePressed

    private void btn_listMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listMousePressed
        // TODO add your handling code here:
        setColor(btn_list);
        resetColor(btn_discover);
        jPanel3.setVisible(true);
        btn_looking.setVisible(true);
        loadData();
    }//GEN-LAST:event_btn_listMousePressed

    private void btn_discoverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_discoverMousePressed
        // TODO add your handling code here:
        setColor(btn_discover);
        resetColor(btn_list);
        jPanel_edit.setVisible(true);
        jButton1.setVisible(true);
    }//GEN-LAST:event_btn_discoverMousePressed

    private void btn_lookingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lookingMousePressed
        // TODO add your handling code here:
        lbl_find.setVisible(true);
        txt_find.setVisible(true);
        btn_rst2.setVisible(true);
        btn_hide.setVisible(true);
    }//GEN-LAST:event_btn_lookingMousePressed

    private void btn_hideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hideMousePressed
        // TODO add your handling code here:
        lbl_find.setVisible(false);
        txt_find.setVisible(false);
        btn_rst2.setVisible(false);
        btn_hide.setVisible(false);
    }//GEN-LAST:event_btn_hideMousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void btn_rstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rstActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btn_rstActionPerformed

    private void btn_lookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lookingActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        txt_1.setText(model.getValueAt(i, 1).toString());
        txt_2.setText(model.getValueAt(i, 3).toString());
        txt_3.setText(model.getValueAt(i, 4).toString());
        txt_4.setText(model.getValueAt(i, 5).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_updateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMousePressed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btn_updateMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        jPanel_edit.setVisible(false);
        jButton1.setVisible(false);
    }//GEN-LAST:event_jButton1MousePressed

    private void txt_findKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_findKeyReleased
        // TODO add your handling code here:
                        try {
            Class.forName(connector);
            Connection con = DriverManager.getConnection(url, user, password);
            String find = txt_find.getText();
            String query = "select id, name, species_name, age, cage_nr, cage_size from animals inner join species using (id_species) where species_name = '" + find + "'";
            PreparedStatement pst = con.prepareStatement(query); 
            ResultSet rs = pst.executeQuery();
                        
                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        if(txt_find.getText().isEmpty()){loadData();}
            
//            while(rs.next()){
//            
//            }
                    
        
        }
        catch(SQLException | ClassNotFoundException ex){
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_findKeyReleased

    private void btn_rst2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rst2MousePressed
        // TODO add your handling code here:
        txt_find.setText("");
    }//GEN-LAST:event_btn_rst2MousePressed

    private void loadData() {
        try {
            Class.forName(connector);
            Connection con = DriverManager.getConnection(url, user, password);
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select id, name, species_name, age, cage_nr, cage_size from animals inner join species using (id_species);");
            {

                while (jTable1.getRowCount() > 0) {
                    ((DefaultTableModel) jTable1.getModel()).removeRow(0);
                }

                int col = rs.getMetaData().getColumnCount();

                while (rs.next()) {
                    Object[] rows = new Object[col];
                    for (int i = 1; i <= col; i++) {
                        rows[i - 1] = rs.getObject(i);
                    }
                    ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow() - 1, rows);
                }
                rs.close();
                st.close();
                con.close();
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void saveData() {
        String name = txt_1.getText();
        int age = Integer.parseInt(txt_2.getText());
        int cage_nr = Integer.parseInt(txt_3.getText());
        String cage_size = txt_4.getText();

        try {
            Class.forName(connector);
            try (
                    Connection con = DriverManager.getConnection(url, user, password);
                    PreparedStatement pstmt = con.prepareStatement("insert into animals values(nextval('id_seq'),?,?,?,?,?)")) {
                pstmt.setString(1, name);
                pstmt.setInt(2, 1);
                pstmt.setInt(3, age);
                pstmt.setInt(4, cage_nr);
                pstmt.setString(5, cage_size);

                int i = pstmt.executeUpdate();

                if (i > 0) {
                    JOptionPane.showMessageDialog(null, "Animal added");
                    lblStatus.setForeground(new Color(0, 179, 0));
                    lblStatus.setText("One animal more on this planet!");
                    loadData();
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(null, "Animal saving failed");
                }
                pstmt.close();
                con.close();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

 private void alterId() {
        try {
            Class.forName(connector);
            Connection con = DriverManager.getConnection(url, user, password);
            PreparedStatement pstmt;
            try (
                    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                    ResultSet rs = st.executeQuery("select * from animals")) {
                int id;
                if (rs.last()) {
                    id = rs.getInt("id");
                    id++;
                    pstmt = con.prepareStatement("alter sequence id_seq restart with " + id);
                    pstmt.executeUpdate();
                    pstmt.close();
                } else {
                    pstmt = con.prepareStatement("alter sequence id_seq restart with 1");
                    pstmt.executeUpdate();
                    pstmt.close();
                }
                rs.close();
                st.close();
                con.close();
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void remove() {
        try {
            Class.forName(connector);
            Connection con = DriverManager.getConnection(url, user, password);
            int row = jTable1.getSelectedRow();
            String value = (jTable1.getModel().getValueAt(row, 0).toString());
            String query = "delete from animals where id = " + value;
            PreparedStatement pst = con.prepareStatement(query);
            pst.executeUpdate();
            alterId();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            loadData();
            JOptionPane.showMessageDialog(null, "The animal killed! Do you have human dignity and understanding?!");
            clearFields();
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void update() {
        String name = txt_1.getText();
        int age = Integer.parseInt(txt_2.getText());
        int cage_nr = Integer.parseInt(txt_3.getText());
        String cage_size = txt_4.getText();
        try {
            Class.forName(connector);
            try (Connection con = DriverManager.getConnection(url, user, password)) {
                int row = jTable1.getSelectedRow();
                String value = (jTable1.getModel().getValueAt(row, 0).toString());
                String query = "update animals set name = ?, age = ?, cage_nr = ?, cage_size = ? where id =" + value;
                try (PreparedStatement pstmt = con.prepareStatement(query)) {
                    pstmt.setString(1, name);
                    pstmt.setInt(2, age);
                    pstmt.setInt(3, cage_nr);
                    pstmt.setString(4, cage_size);

                    int i = pstmt.executeUpdate();

                    if (i > 0) {
                        JOptionPane.showMessageDialog(null, "Animal's data updated!");
                        lblStatus.setForeground(new Color(0, 179, 0));
                        lblStatus.setText("Animal's data updated!");
                        loadData();
                        clearFields();
                    } else {
                        JOptionPane.showMessageDialog(null, "Animal data changing failed");
                    }
                    pstmt.executeUpdate();
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    

    private void clearFields() {
        txt_1.setText("");
        txt_2.setText("");
        txt_3.setText("");
        txt_4.setText("");
    }

    private void setColor(JPanel panel) {
        panel.setBackground(new Color(135, 112, 225));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(76, 41, 211));
    }

    private void centerFrame() {
        Toolkit toolkit;
        toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }
    
//    private void save_or_update(){
//        try{
//            Class.forName(connector);
//            Connection con = DriverManager.getConnection(url, user, password);
//            ResultSet rs = con.prepareStatement("select insert_or_update_animals(?)").executeQuery();
//        }
//        
//        catch(ClassNotFoundException | SQLException ex){
//        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//    
//    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JPanel btn_discover;
    private javax.swing.JButton btn_hide;
    private javax.swing.JPanel btn_list;
    private javax.swing.JButton btn_looking;
    private javax.swing.JButton btn_rmv;
    private javax.swing.JButton btn_rst;
    private javax.swing.JButton btn_rst2;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_4;
    private javax.swing.JLabel lbl_discover;
    private javax.swing.JLabel lbl_find;
    private javax.swing.JLabel lbl_list;
    private javax.swing.JLabel lbll_3;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_2;
    private javax.swing.JTextField txt_3;
    private javax.swing.JTextField txt_4;
    private javax.swing.JTextField txt_find;
    // End of variables declaration//GEN-END:variables
}
